name: tensor-right
version: 0.1.0.0
synopsis: Automated Verification of Tensor Graph Rewrites
description: |
  TensorRight is an automatic tool that can be used to verify
  Tensor Graph Rewrites.
license: Apache-2.0
license-file: LICENSE

dependencies:
  - base >= 4.14 && < 5
  - grisette >= 0.11 && < 0.12
  - unordered-containers
  - text
  - mtl
  - hashable
  - prettyprinter
  - ordered-containers
  - deepseq
  - sbv
  - template-haskell

library:
  source-dirs: src
  ghc-options:
    - -Wextra
    - -Wcompat
    - -Widentities
    - -Wincomplete-record-updates
    - -Wmissing-export-lists
    - -Wmissing-home-modules
    - -Wmissing-import-lists
    - -Wpartial-fields
    - -Wunused-type-patterns
    - -Wno-x-partial
    - -Wno-unrecognised-warning-flags

_exe-ghc-options: &exe-ghc-options
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N

_exe-extensions: &exe-extensions
  - DuplicateRecordFields
  - OverloadedStrings
  - TypeApplications
  - AllowAmbiguousTypes
  - ScopedTypeVariables
  - FlexibleContexts
  - RankNTypes

executables:
  # XLA Executables
  rules-xla-add:
    source-dirs: rules/xla/add
    main: Main.hs
    dependencies: tensor-right
    ghc-options: *exe-ghc-options
    default-extensions: *exe-extensions
  rules-xla-mul:
    source-dirs: rules/xla/mul
    main: Main.hs
    dependencies: tensor-right
    ghc-options: *exe-ghc-options
    default-extensions: *exe-extensions
  rules-xla-reduce:
    source-dirs: rules/xla/reduce
    main: Main.hs
    dependencies: tensor-right
    ghc-options: *exe-ghc-options
    default-extensions: *exe-extensions
  rules-xla-compare:
    source-dirs: rules/xla/compare
    main: Main.hs
    dependencies: tensor-right
    ghc-options: *exe-ghc-options
    default-extensions: *exe-extensions
  rules-xla-slice:
    source-dirs: rules/xla/slice
    main: Main.hs
    dependencies: tensor-right
    ghc-options: *exe-ghc-options
    default-extensions: *exe-extensions
  rules-xla-iota:
    source-dirs: rules/xla/iota
    main: Main.hs
    dependencies: tensor-right
    ghc-options: *exe-ghc-options
    default-extensions: *exe-extensions
  rules-xla-pad:
    source-dirs: rules/xla/pad
    main: Main.hs
    dependencies: tensor-right
    ghc-options: *exe-ghc-options
    default-extensions: *exe-extensions
  rules-xla-dyslice:
    source-dirs: rules/xla/dyslice
    main: Main.hs
    dependencies: tensor-right
    ghc-options: *exe-ghc-options
    default-extensions: *exe-extensions
  rules-xla-dyupslice:
    source-dirs: rules/xla/dyupslice
    main: Main.hs
    dependencies: tensor-right
    ghc-options: *exe-ghc-options
    default-extensions: *exe-extensions
  rules-xla-broadcast:
    source-dirs: rules/xla/broadcast
    main: Main.hs
    dependencies: tensor-right
    ghc-options: *exe-ghc-options
    default-extensions: *exe-extensions
  rules-xla-concat:
    source-dirs: rules/xla/concat
    main: Main.hs
    dependencies: tensor-right
    ghc-options: *exe-ghc-options
    default-extensions: *exe-extensions
  rules-xla-logical:
    source-dirs: rules/xla/logical
    main: Main.hs
    dependencies: tensor-right
    ghc-options: *exe-ghc-options
    default-extensions: *exe-extensions
  rules-xla-relabel:
    source-dirs: rules/xla/relabel
    main: Main.hs
    dependencies: tensor-right
    ghc-options: *exe-ghc-options
    default-extensions: *exe-extensions
  rules-xla-dot:
    source-dirs: rules/xla/dot
    main: Main.hs
    dependencies: tensor-right
    ghc-options: *exe-ghc-options
    default-extensions: *exe-extensions
  rules-xla-conv:
    source-dirs: rules/xla/conv
    main: Main.hs
    dependencies: tensor-right
    ghc-options: *exe-ghc-options
    default-extensions: *exe-extensions
  rules-xla-max:
    source-dirs: rules/xla/max
    main: Main.hs
    dependencies: tensor-right
    ghc-options: *exe-ghc-options
    default-extensions: *exe-extensions
  rules-xla-not:
    source-dirs: rules/xla/not
    main: Main.hs
    dependencies: tensor-right
    ghc-options: *exe-ghc-options
    default-extensions: *exe-extensions
  rules-xla-clamp:
    source-dirs: rules/xla/clamp
    main: Main.hs
    dependencies: tensor-right
    ghc-options: *exe-ghc-options
    default-extensions: *exe-extensions
  rules-xla-select:
    source-dirs: rules/xla/select
    main: Main.hs
    dependencies: tensor-right
    ghc-options: *exe-ghc-options
    default-extensions: *exe-extensions
  rules-xla-reverse:
    source-dirs: rules/xla/reverse
    main: Main.hs
    dependencies: tensor-right
    ghc-options: *exe-ghc-options
    default-extensions: *exe-extensions
  rules-xla-sub:
    source-dirs: rules/xla/sub
    main: Main.hs
    dependencies: tensor-right
    ghc-options: *exe-ghc-options
    default-extensions: *exe-extensions
  rules-xla-divmod:
    source-dirs: rules/xla/divmod
    main: Main.hs
    dependencies: tensor-right
    ghc-options: *exe-ghc-options
    default-extensions: *exe-extensions
  rules-xla-generalize:
    source-dirs: rules/xla/generalize
    main: Main.hs
    dependencies: tensor-right
    ghc-options: *exe-ghc-options
    default-extensions: *exe-extensions
  rules-xla-test1:
    source-dirs: rules/xla/test1
    main: Main.hs
    dependencies: tensor-right
    ghc-options: *exe-ghc-options
    default-extensions: *exe-extensions
  # Other Executables
  rules-debug:
    source-dirs: rules/debug
    main: Main.hs
    dependencies: tensor-right
    ghc-options: *exe-ghc-options
    default-extensions: *exe-extensions

tests:
  spec:
    main: Main.hs
    source-dirs: test
    dependencies:
      - tensor-right
      - test-framework >= 0.8.2 && < 0.9
      - test-framework-hunit >= 0.3.0.2 && < 0.4
      - test-framework-quickcheck2 >= 0.3.0.5 && < 0.4
      - HUnit >= 1.6
      - QuickCheck
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
